# minimal DOSBox-Staging 0.83.0 configuration file for CompoKit

[sdl]
fullscreen=true

[dosbox]
language=en

[render]
aspect=true
glshader=sharp

[cpu]
core=dynamic
cycles=max

[mixer]
rate=48000

[midi]
mpu401=uart
# Use SC-55 by default; set to 'win32' for the default Microsoft synth
mididevice=soundcanvas

[gus]
gus=true

[speaker]
pcspeaker=discrete
lpt_dac=covox

[soundcanvas]
soundcanvas_model=sc55_121
# when copying this file, make sure to adapt the path here
# (CompoKit's default cklaunch.ini ensures that the path is set correctly
# when running a .com file with Alt+Enter, but if you copy the config file.
# you're on your own here)
soundcanvas_rom_dir=C:\PATH\TO\COMPOKIT\BIN\soundcanvas-roms
